### ISSUE TITLE
AI Occlusion Box Modification: Incorrect Behavior with Multiple Groups

### ISSUE THREAD

**Issue by Havoc-1** [SilenceIsFatto/HATG#23]
If players are hidden from a group (e.g., Group A) due to grass or other occlusions, the modification correctly spawns an occlusion box around the players.

However, if another group (e.g., Group B) approaches from a different angle where there is no occlusion (grass or object), the occlusion box remains active, preventing Group B from seeing the players even if they are within close proximity.

This leads to an inconsistent and unrealistic situation where players can remain hidden from all enemy groups, regardless of their actual visibility, as long as they are initially hidden from one group.
See attached image for visualization.

![image](https://github.com/user-attachments/assets/c7a6d645-dd4f-45d0-aab9-d076fa89eaa9)

**Comment by SilenceIsFatto** [comment]
HATG doesn't care if you're blocked by actual "grass" strands as it's inefficient to check that every second. It also doesn't care if AI have direct LOS to you for the same reason. This is why we prefer the term "Hide ***Among*** The Grass".

It uses general and simple approaches of checking if you are on "grass" terrain and checking if enemies are near you instead. Simplicity beats complexity

What you show here is more akin to ACSTG rather than HATG. The method that ACSTG uses is remarkably inefficient

The behaviour you describe is not because of 2 groups interacting, it's simply how the mod works. Do note however that the distance check is currently a bit odd and easily exploitable which will be changed in a future update. With enemies that close you should've already been revealed

**Comment by Havoc-1** [comment]
Thank you for your reply. However, comparing HATG to ACSTG is **misleading**. The differences between the two mods go beyond performance and have distinctly different feature sets. Naturally, HATG will perform better because it offers a more limited scope of functionality. 

If HATG is meant to be a simpler and more efficient alternative to ACSTG, that should be explicitly stated along with its **limitations**. When a modification is directly being compared to as an alternative there is an expectation of gameplay experience being similar (or more as you state in the workshop) if they have used the compared modification previously. 

As it stands, the expectation might be that HATG offers a similar set of features to ACSTG but with better performance, while in reality, it trades off key aspects of visibility handling to achieve this when scaled. When players encounter the described behavior—it undermines the expectations you set in your description and can be confusing without proper explanation. Being transparent about these differences would help avoid such misunderstandings.

**Comment by SilenceIsFatto** [comment]
In terms of **functionality**, you can do the same things that you can in ACSTG. HATG does not offer a "limited scope of functionality", it cuts out the poorly performant and sometimes borderline useless bloat.

"Limited scope of functionality" tells me you haven't actually tested the mod at all and you simply came to a conclusion the second you saw one thing that wasn't exactly as you thought it would be.

Regardless, I appreciate you spending the time to open an issue!
